# Site settings
title: Blog of Michael, son of Ander
header-img: img/home-bg.png
email: michanders@msn.com
copyright_name: michanders
description: > # this means to ignore newlines until "baseurl:"
  Learning lots. Lots to learn.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: MikeMan
github_username:  michanders
learn_profile: michanders
email_username: michanders@msn.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
